[package]
name = "zephyr"
version = "0.1.0"
edition = "2021"

[features]
default = []

inventory = ["dep:inventory"]

[dependencies]
inventory = { version = "0.3", optional = true }
tracing = "0.1.35"

[[example]]
name = "inventory"
required-features = ["inventory"]
